### PR TITLE
Add -region flag

### PR DESCRIPTION
**Pull request by thomasf**

### CODE REVIEW

**Comment by alexaandru** [comment]
Thank you for the PR, looks like a good change :) Cheers!

**Comment by thomasf** [comment]
sorry for breaking tests.. fixing that now.. Forgot about it.

**Comment by thomasf** [comment]
TestBetterMime fails for me, seems unrelated.

**Comment by thomasf** [comment]
The assuption that  ".ttf" will become  "binary/octet-stream" is wrong because on my system .ttf is already defined as `application/font-sfnt`. The `betterMime` function prioritizes default system mime types  so that test will behave differently depending on the system it is run on.,

**Comment by thomasf** [comment]
btw. You can add mime types directly in go by using  the `mime.AddExtensionType` function,.

**Comment by alexaandru** [comment]
Thank you for the fix and all the feedback. Good to know about `mime.AddExtensionType` :) As for the MIME type I set for .ttf - that is not about what MIME type these files have locally, is about the MIME type I want them to have the uploaded to S3. And I needed something that works with HTML/browsers and will actually be interpreted as a font (or well, "something" that should be downloaded rather).

I also have a MIME type set for these locally (application/x-font-ttf) but somehow that didn't work as expected (fonts were ignored). Though I don't remember if Go even picked that one up or not, and it looks like not: http://play.golang.org/p/Y9pwITkYvN (also ran it locally, the result is empty string as well). So that's the reason for the hardcoding.

**Pull request merged**
